In [35]:
import numpy as np
import random
from collections import deque


In [36]:
def q_learning(total_episodes, running_time, plot_every=100):

    states = [0, 1 ,2]
    actions = [0, 1]
    reward_function = {0:[5, 3], 1:[2, 4], 2:[6, 1]}
    qtable = np.zeros((len(states), len(actions)))

    learning_rate = 0.1
    gamma = 0.9

    rewards = []
    tmp_scores = deque(maxlen=plot_every)     # deque for keeping track of scores
    avg_scores = deque(maxlen=total_episodes)   # average scores over every plot_every episodes

    for episode in range(total_episodes + 1):
        state = random.choice(states)
        now = 0
        total_rewards = 0 # collected reward within an episode
        if episode % 100 == 0: #monitor progress
            print("\rEpisode {}/{} \n".format(episode, total_episodes), end="") 
        
        while True:
            if random.random() < 0.1:
                action = random.choice(actions)
            else:
                action = np.argmax(qtable[state])
            #print(state, action, rewards)
            reward = -reward_function[state][action]
            now += -reward

            new_state = random.choice(states)
                        
            # Update Q(s,a):= Q(s,a) + lr [R(s,a) + gamma * max Q(s',a') - Q(s,a)]

            #print('this',(1 - self.learning_rate) * self.qtable[state[0].task_type][self.simulator.resources.index(action), self.workloads.index(workload)] +\
            #																								self.learning_rate * (reward + self.gamma * max_value_next_state))
            qtable[state, action] = (1 - learning_rate) * qtable[state, action] + learning_rate * (reward + gamma * max(qtable[new_state, :]))
            
            #print(self.qtable[state[0].task_type][self.simulator.resources.index(action), self.workloads.index(workload)])
            total_rewards += reward # sum the rewards collected within an episode
            state = new_state
            if now > running_time:
                tmp_scores.append(total_rewards)
                #print(self.qtable)
                print(qtable, '\n')
                break
        if (episode % plot_every == 0): #for plot
            avg_scores.append(np.mean(tmp_scores))
        
        rewards.append(total_rewards)

In [37]:
q_learning(100000, running_time=10000)

Episode 0/100000 
[[-22.56340152 -20.58283793]
 [-19.61413685 -21.61808569]
 [-23.53502125 -18.4093409 ]] 

[[-22.86943394 -20.75880839]
 [-19.48186683 -22.11334084]
 [-23.53041068 -18.62109584]] 

[[-22.80720459 -21.04541707]
 [-19.85309644 -21.92427777]
 [-23.93964621 -19.02363022]] 

[[-23.34395555 -21.18609939]
 [-20.40788019 -22.01454004]
 [-24.05939928 -19.13555423]] 

[[-23.05698947 -21.0079921 ]
 [-19.96836547 -21.87088235]
 [-24.05586175 -19.0485088 ]] 

[[-23.30573184 -21.13254264]
 [-19.86053401 -22.29388525]
 [-23.93567021 -18.85515836]] 

[[-23.06646678 -21.19465258]
 [-20.61665984 -22.00290129]
 [-23.87074719 -19.43927801]] 

[[-22.82797229 -20.92030098]
 [-19.99004862 -21.61548243]
 [-23.80065621 -18.80363126]] 

[[-23.21403499 -20.48080693]
 [-19.61601294 -21.77433211]
 [-23.808713   -18.48818059]] 

[[-23.0495612  -20.9882153 ]
 [-20.0933905  -22.2875207 ]
 [-24.45978002 -19.18930946]] 

[[-22.74592629 -21.0905901 ]
 [-20.09517255 -21.91071929]
 [-24.12952507 -19.28920

KeyboardInterrupt: 